// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE5Jll6q0bnpuHYR7xbICTdvxgRiFzzAw',
    appId: '1:1081799820560:web:e57ab6812797744b611195',
    messagingSenderId: '1081799820560',
    projectId: 'my-learning-project-cb451',
    authDomain: 'my-learning-project-cb451.firebaseapp.com',
    storageBucket: 'my-learning-project-cb451.appspot.com',
    measurementId: 'G-67V8EW4Z25',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNL9Ui4j2LdeAWi-WNRLnBFXW9hokOrHg',
    appId: '1:1081799820560:android:183fb6d56940bc94611195',
    messagingSenderId: '1081799820560',
    projectId: 'my-learning-project-cb451',
    storageBucket: 'my-learning-project-cb451.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCgVP3byUv2ybPZtPn33LuVG1Ai0zrqud0',
    appId: '1:1081799820560:ios:12e84f27724495f6611195',
    messagingSenderId: '1081799820560',
    projectId: 'my-learning-project-cb451',
    storageBucket: 'my-learning-project-cb451.appspot.com',
    iosClientId: '1081799820560-t9eurh48rshq5bnear3t5g9q2r5bpej8.apps.googleusercontent.com',
    iosBundleId: 'com.example.learningdart',
  );
}
